name : swig
version: 4.0.0

source:
git_url: https://github.com/swig/swig.git

requirement:
  build:
    - automake
    - autoconf
    - libtool
    - libpcre3-dev
    - python
  run:
    - pcre
test:
  commands:
    - swig --help

about:
  home: http://www.swig.org/
  license: GPLv3
  summary: C/C++ parser code generator
